import Header from '@/components/Header'
import './globals.css'
import { Roboto } from 'next/font/google'

const inter = Roboto({ subsets: ['latin'] , weight : ['400'] })

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        </body>
    </html>
  )
}
